### Python_Programming_Assignment_8

#### 1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

np.random.seed(1)
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(f"First matrix is {a}")
print(f"Second matrix is {b}")
print("Matrix Addition is as follows:")
print(a+b)

First matrix is [[6 9 6]
 [1 1 2]
 [8 7 3]]
Second matrix is [[5 6 3]
 [5 3 5]
 [8 8 2]]
Matrix Addition is as follows:
[[11 15  9]
 [ 6  4  7]
 [16 15  5]]


#### 2. Write a Python Program to Multiply Two Matrices?

In [2]:
np.random.seed(2)
a = np.random.randint(1,10,(3,3))
b = np.random.randint(1,10,(3,3))
print(f"First matrix is {a}")
print(f"Second matrix is {b}")
print("Matrix Multiplication is as follows:")
print(a*b)

First matrix is [[9 9 7]
 [3 9 8]
 [3 2 6]]
Second matrix is [[5 5 6]
 [8 4 7]
 [5 4 8]]
Matrix Multiplication is as follows:
[[45 45 42]
 [24 36 56]
 [15  8 48]]


#### 3. Write a Python Program to Transpose a Matrix?

In [3]:
np.random.seed(3)
a = np.random.randint(1,10,(3,3))
print(f"Before transposig matrix is {a}")
print(f"After transposing matrix is {np.transpose(a)}")

Before transposig matrix is [[9 4 9]
 [9 1 6]
 [4 6 8]]
After transposing matrix is [[9 9 4]
 [4 1 6]
 [9 6 8]]


#### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [4]:
a = ['t', 'g', 'a', 'b', 'f','c', 'z']
a.sort()
a

['a', 'b', 'c', 'f', 'g', 't', 'z']

#### 5. Write a Python Program to Remove Punctuation From a String?

In [5]:
string = "gkn!kk()[]hdmdsosm<djd@#jn%$^"
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
for i in string:
  if i in punc:
    string = string.replace(i,"")

string

'gknkkhdmdsosmdjdjn'